### ISSUE TITLE
Every call to cargo hakai crashes

### ISSUE THREAD

**Issue by dsxmachina** [guppy-rs/guppy#313] opened 2024-08-08 07:47 UTC
Hello,

I don't know, what I did with my project - but it crashes cargo hakari everytime I call it.
It doesn't matter what I do so:
```
cargo hakari generate
```
does not work, and so does
```
cargo hakari manage-deps
```
and even
```
cargo hakari disable
# and
cargo hakari remove-deps
```

I manually removed the workspace-hack crate and tried to re-generate with:
```
cargo hakari init
```
But get the same error. This is the backtrace of the error:
```
The application panicked (crashed).
Message:  at least one dependency instance
Location: guppy/src/graph/build.rs:749

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 6 frames hidden ⋮
   7: core::panicking::panic_display::hd8c516c36ffd47b9
      at <unknown source file>:<unknown line>
   8: core::option::expect_failed::hcf48fdb9c93a315f
      at <unknown source file>:<unknown line>
   9: guppy::graph::build::<impl guppy::graph::graph_impl::PackageLinkImpl>::new::hedf2670bfc5d735a
      at <unknown source file>:<unknown line>
  10: guppy::graph::build::GraphBuildState::process_package::h1e686e1af0aa23dc
      at <unknown source file>:<unknown line>
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h065c206c794d6246
      at <unknown source file>:<unknown line>
  12: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter::h005752c8e4328f54
      at <unknown source file>:<unknown line>
  13: guppy::graph::graph_impl::PackageGraph::from_metadata::hd00ea1052109d3b2
      at <unknown source file>:<unknown line>
  14: guppy::metadata_command::MetadataCommand::build_graph::hb4eb386b1a3608c3
      at <unknown source file>:<unknown line>
  15: cargo_hakari::command::Command::exec::h7a5b849e3e609f76
      at <unknown source file>:<unknown line>
  16: cargo_hakari::command::Args::exec::h39f6b998ce719c52
      at <unknown source file>:<unknown line>
  17: cargo_hakari::main::h0114ffb1046d9c78
      at <unknown source file>:<unknown line>
  18: std::sys_common::backtrace::__rust_begin_short_backtrace::h3fea250e0aeb62b9
      at <unknown source file>:<unknown line>
  19: std::rt::lang_start::{{closure}}::h07d4fa1872ec0b13
      at <unknown source file>:<unknown line>
  20: std::panicking::try::h9134436c64049e5f
      at <unknown source file>:<unknown line>
  21: std::rt::lang_start_internal::hf4417b67ea9bae52
      at <unknown source file>:<unknown line>
  22: main<unknown>
      at <unknown source file>:<unknown line>
  23: __libc_start_call_main<unknown>
      at <unknown source file>:<unknown line>
  24: __libc_start_main@@GLIBC_2.34<unknown>
      at <unknown source file>:<unknown line>
  25: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

Please let me know, if you need any additional inforamation.

**Comment by sunshowers** [comment] 2024-08-08 23:03
Hi there --

This looks like an issue that has been resolved. Could you try updating to a newer version of hakari? Thanks.

**Comment by dsxmachina** [comment] 2024-08-13 11:11
Could you give me a little bit more information here ? Which version resolves the problem?
I am using 
```
cargo-hakari 0.9.28
```
which is the newest version, that is available to me via nix-flakes

**Comment by sunshowers** [comment] 2024-08-13 15:27
This issue was resolved in version 0.9.29. Nix packages are community-maintained and might not always be the latest version. Please do try again with the latest version available on crates.io (currently 0.9.30), thanks!

**Comment by ShaddyDC** [comment] 2024-08-14 10:00
Looks like it was updated in nixpkgs recently: https://github.com/NixOS/nixpkgs/pull/331820

It should be available in nixpkgs-unstable by now, so you might need to run `nix flake update`. I can confirm that that fixes the issue on my end.

**Comment by sunshowers** [comment] 2024-08-31 05:53
This should be resolved so I'm going to go ahead and close this. Thanks!

**Closed by sunshowers** 2024-08-31 05:53 UTC
